version: "3.8"

services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: landeployer
      TZ: Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - lan-network

  mysqld-exporter:
    image: prom/mysqld-exporter:v0.15.0
    container_name: mysqld_exporter
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: "root:root@123@(mysql:3306)/"
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - lan-network

networks:
  lan-network:
    driver: bridge

volumes:
  mysql_data:

