version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - lan-network

  redis-exporter:
    image: oliver006/redis_exporter:v1.55.0
    container_name: redis_exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis://redis:6379"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - lan-network

networks:
  lan-network:
    driver: bridge

volumes:
  redis_data:

